### ISSUE TITLE
Moodle 2.7 deprecated warnings

### ISSUE THREAD

**Issue by ruddj** [davosmith/moodle-assignsubmission_pdf#5]
Thanks for the great plugin. Just been testing on Moodle 2.7 and appears to work fine, but I am getting some warnings when debugging shows notices.

When saving a submission receive this:
```
events_trigger() is deprecated, please use new events instead
line 283 of /lib/deprecatedlib.php: call to debugging()
line 367 of /mod/assign/submission/pdf/locallib.php: call to events_trigger()
line 5672 of /mod/assign/locallib.php: call to assign_submission_pdf->save()
line 5741 of /mod/assign/locallib.php: call to assign->save_submission()
line 395 of /mod/assign/locallib.php: call to assign->process_save_submission()
line 53 of /mod/assign/view.php: call to assign->view()
```

And when submitting PDF feedback receive this:
```
Invalid get_string() identifier: 'feedback' or component 'assignment'. Perhaps you are missing $string['feedback'] = ''; in mod/assignment/lang/en/assignment.php?
line 293 of /lib/classes/string_manager_standard.php: call to debugging()
line 6926 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 572 of /mod/assign/feedback/pdf/locallib.php: call to get_string()
line 68 of /mod/assign/feedback/pdf/editcomment.php: call to assign_feedback_pdf->edit_comment_page()
```

**Comment by davosmith** [comment]
Thanks, I'll try to take a look at this (although I generally advise people to try and use the built-in PDF annotation from 2.6 onwards - it's pretty much the same functionality, but tidied up a bit and (hopefully) better maintained).

**Comment by ruddj** [comment]
Thanks Dave. I didn't realise that PDF annotation was now in core.
To go to using the core option is there anyway to convert submitted assignments using PDF Submission to be standard file submissions? Thank you.

**Comment by davosmith** [comment]
Sorry for the extremely slow reply.

The event_trigger warning is now fixed. I think the other issue was fixed a while back.

There is no existing way to transition from PDF submission to standard file submissions, but new assignments should probably use the standard file submissions (unless the coversheet functionality is required).
